DROP TABLE IF EXISTS Seasosns;


--alter table seasons add id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- CREATE TABLE Seasons (
--	id serial primary key,
--   year VARCHAR(250),
--   url VARCHAR(250)
--);